#! /usr/bin/env python
# $Id: run_tests,v 1.1.1.1 2002/05/06 07:31:09 richard Exp $

from test import go
import sys
if len(sys.argv) > 1:
    go(sys.argv[1:])
else:
    go()

#
# $Log: run_tests,v $
# Revision 1.1.1.1  2002/05/06 07:31:09  richard
#
#
#
#
# vim: set filetype=python ts=4 sw=4 et si
