import re

from wxPython.wx import *
# from wxPython.html import *
import wxPython.xrc as xrc

from wxHelper import *

from StringOps import uniToGui, guiToUni, htmlColorToRgbTuple,\
        rgbToHtmlColor

from AdditionalDialogs import DateformatDialog, FontFaceDialog


class OptionsDialog(wxDialog):
    # List of tuples (<configuration file entry>, <gui control name>, <type>)
    # Supported types: b: boolean checkbox, i0+: nonnegative integer, t: text
    #    tre: regular expression,  f0+: nonegative float, seli: integer position
    #    of a selection in dropdown list,  color0: HTML color code or empty

    OPTION_TO_CONTROL = (
            # application-wide options
            
            ("auto_save", "cbAutoSave", "b"),
            ("auto_save_delay_key_pressed", "tfAutoSaveDelayKeyPressed", "i0+"),
            ("auto_save_delay_dirty", "tfAutoSaveDelayDirty", "i0+"),

            ("showontray", "cbShowOnTray", "b"),
            ("minimize_on_closeButton", "cbMinimizeOnCloseButton", "b"),

            ("hideundefined", "cbHideUndefinedWords", "b"),
            ("process_autogenerated_areas", "cbProcessAutoGenerated", "b"),
            ("script_security_level", "chScriptSecurityLevel", "seli"),
            ("pagestatus_timeformat", "tfPageStatusTimeFormat", "t"),
            ("log_window_autoshow", "cbLogWindowAutoShow", "b"),
            ("log_window_autohide", "cbLogWindowAutoHide", "b"),
            ("clipboardCatcher_suffix", "tfClipboardCatcherSuffix", "t"),
            ("single_process", "cbSingleProcess", "b"),

            ("mainTree_position", "chMainTreePosition", "seli"),
            ("viewsTree_position", "chViewsTreePosition", "seli"),

            ("tree_auto_follow", "cbTreeAutoFollow", "b"),
            ("tree_update_after_save", "cbTreeUpdateAfterSave", "b"),
            ("tree_no_cycles", "cbTreeNoCycles", "b"),
            
            ("start_browser_after_export", "cbStartBrowserAfterExport", "b"),
            ("facename_html_preview", "tfFacenameHtmlPreview", "t"),
            ("html_preview_proppattern_is_excluding",
                    "cbHtmlPreviewProppatternIsExcluding", "b"),
            ("html_preview_proppattern", "tfHtmlPreviewProppattern", "tre"),
            ("html_export_proppattern_is_excluding",
                    "cbHtmlExportProppatternIsExcluding", "b"),
            ("html_export_proppattern", "tfHtmlExportProppattern", "tre"),
            ("html_preview_pics_as_links", "cbHtmlPreviewPicsAsLinks", "b"),
            ("html_export_pics_as_links", "cbHtmlExportPicsAsLinks", "b"),
            
            ("html_body_link", "tfHtmlLinkColor", "color0"),
            ("html_body_alink", "tfHtmlALinkColor", "color0"),
            ("html_body_vlink", "tfHtmlVLinkColor", "color0"),
            ("html_body_text", "tfHtmlTextColor", "color0"),
            ("html_body_bgcolor", "tfHtmlBgColor", "color0"),
            ("html_body_background", "tfHtmlBgImage", "t"),

            ("editor_plaintext_color", "tfEditorPlaintextColor", "color0"),
            ("editor_link_color", "tfEditorLinkColor", "color0"),
            ("editor_attribute_color", "tfEditorAttributeColor", "color0"),
            ("editor_bg_color", "tfEditorBgColor", "color0"),
            ("sync_highlight_byte_limit", "tfSyncHighlightingByteLimit", "i0+"),
            ("async_highlight_delay", "tfAsyncHighlightingDelay", "f0+"),
            ("editor_autoUnbullets", "cbAutoUnbullets", "b"),

            # wiki specific options

            ("footnotes_as_wikiwords", "cbFootnotesAsWws", "b"),
            ("first_wiki_word", "tfFirstWikiWord", "t"),

            ("wikiPageTitlePrefix", "tfWikiPageTitlePrefix", "t"),

            ("fileStorage_identity_modDateMustMatch", "cbFsModDateMustMatch", "b"),
            ("fileStorage_identity_filenameMustMatch", "cbFsFilenameMustMatch", "b"),
            ("fileStorage_identity_modDateIsEnough", "cbFsModDateIsEnough", "b")
    )

    _PANEL_LIST = (
            ("OptionsPageApplication", u"Application"),    
            ("OptionsPageTree", u"  Tree"),
            ("OptionsPageHtml", u"  HTML preview/export"),
            ("OptionsPageAutosave", u"  Autosave"),
            ("OptionsPageEditor", u"  Editor"),
            ("OptionsPageCurrentWiki", u"Current Wiki")
    )

    def __init__(self, pWiki, ID, title="Options",
                 pos=wxDefaultPosition, size=wxDefaultSize,
                 style=wxNO_3D):
        d = wxPreDialog()
        self.PostCreate(d)
        
        self.pWiki = pWiki
        res = xrc.wxXmlResource.Get()
        res.LoadOnDialog(self, self.pWiki, "OptionsDialog")

        self.ctrls = XrcControls(self)
        
        self.emptyPanel = None

        self.panelList = []
        self.ctrls.lbPages.Clear()
        
        minw = 0
        minh = 0        
        for pn, pt in self._PANEL_LIST:
            if pn:
                panel = res.LoadPanel(self.ctrls.panelPages, pn)
            else:
                if self.emptyPanel is None:
                    # Necessary to avoid a crash        
                    self.emptyPanel = wxPanel(self.ctrls.panelPages)
                    self.emptyPanel.Fit()
                panel = self.emptyPanel
                
            self.panelList.append(panel)
            self.ctrls.lbPages.Append(pt)
            mins = panel.GetSize()
            minw = max(minw, mins.width)
            minh = max(minh, mins.height)

        self.ctrls.panelPages.SetMinSize(wxSize(minw + 10, minh + 10))
        self.Fit()

        self.ctrls.btnOk.SetId(wxID_OK)
        self.ctrls.btnCancel.SetId(wxID_CANCEL)

        # Transfer options to dialog
        for o, c, t in self.OPTION_TO_CONTROL:
            if t == "b":   # boolean field = checkbox
                self.ctrls[c].SetValue(
                        self.pWiki.getConfig().getboolean("main", o))
            elif t in ("t", "tre", "i0+", "f0+", "color0"):  # text field or regular expression field
                self.ctrls[c].SetValue(
                        uniToGui(self.pWiki.getConfig().get("main", o)) )
            elif t == "seli":   # Selection -> transfer index
                self.ctrls[c].SetSelection(
                        self.pWiki.getConfig().getint("main", o))

        # Options with special treatment
        self.ctrls.cbLowResources.SetValue(
                self.pWiki.getConfig().getint("main", "lowresources") != 0)

        self.ctrls.cbNewWindowWikiUrl.SetValue(
                self.pWiki.getConfig().getint("main",
                "new_window_on_follow_wiki_url") != 0)

        self.ctrls.lbPages.SetSelection(0)  
        self._refreshForPage()

        EVT_LISTBOX(self, GUI_ID.lbPages, self.OnLbPages)

        EVT_BUTTON(self, wxID_OK, self.OnOk)
        EVT_BUTTON(self, GUI_ID.btnSelectFaceHtmlPrev, self.OnSelectFaceHtmlPrev)

        EVT_BUTTON(self, GUI_ID.btnSelectHtmlLinkColor,
                lambda evt: self.selectColor(self.ctrls.tfHtmlLinkColor))
        EVT_BUTTON(self, GUI_ID.btnSelectHtmlALinkColor,
                lambda evt: self.selectColor(self.ctrls.tfHtmlALinkColor))
        EVT_BUTTON(self, GUI_ID.btnSelectHtmlVLinkColor,
                lambda evt: self.selectColor(self.ctrls.tfHtmlVLinkColor))
        EVT_BUTTON(self, GUI_ID.btnSelectHtmlTextColor,
                lambda evt: self.selectColor(self.ctrls.tfHtmlTextColor))
        EVT_BUTTON(self, GUI_ID.btnSelectHtmlBgColor,
                lambda evt: self.selectColor(self.ctrls.tfHtmlBgColor))

        EVT_BUTTON(self, GUI_ID.btnSelectEditorPlaintextColor,
                lambda evt: self.selectColor(self.ctrls.tfEditorPlaintextColor))
        EVT_BUTTON(self, GUI_ID.btnSelectEditorLinkColor,
                lambda evt: self.selectColor(self.ctrls.tfEditorLinkColor))
        EVT_BUTTON(self, GUI_ID.btnSelectEditorAttributeColor,
                lambda evt: self.selectColor(self.ctrls.tfEditorAttributeColor))
        EVT_BUTTON(self, GUI_ID.btnSelectEditorBgColor,
                lambda evt: self.selectColor(self.ctrls.tfEditorBgColor))

        EVT_BUTTON(self, GUI_ID.btnSelectPageStatusTimeFormat,
                self.OnSelectPageStatusTimeFormat)


    def _refreshForPage(self):
        for p in self.panelList:
            p.Show(False)
            p.Enable(False)
            
        panel = self.panelList[self.ctrls.lbPages.GetSelection()]

        # Enable appropriate addit. options panel
        panel.Enable(True)
        panel.Show(True)


    def OnLbPages(self, evt):
        self._refreshForPage()
        evt.Skip()


    def OnOk(self, evt):
        fieldsValid = True
        # First check validity of field contents
        for o, c, t in self.OPTION_TO_CONTROL:
            if t == "tre":
                # Regular expression field, test if re is valid
                try:
                    rexp = guiToUni(self.ctrls[c].GetValue())
                    re.compile(rexp, re.DOTALL | re.UNICODE | re.MULTILINE)
                    self.ctrls[c].SetBackgroundColour(wxWHITE)
                except:   # TODO Specific exception
                    fieldsValid = False
                    self.ctrls[c].SetBackgroundColour(wxRED)
            elif t == "i0+":
                # Nonnegative integer field
                try:
                    val = int(guiToUni(self.ctrls[c].GetValue()))
                    if val < 0:
                        raise ValueError
                    self.ctrls[c].SetBackgroundColour(wxWHITE)
                except ValueError:
                    fieldsValid = False
                    self.ctrls[c].SetBackgroundColour(wxRED)
            elif t == "f0+":
                # Nonnegative float field
                try:
                    val = float(guiToUni(self.ctrls[c].GetValue()))
                    if val < 0:
                        raise ValueError
                    self.ctrls[c].SetBackgroundColour(wxWHITE)
                except ValueError:
                    fieldsValid = False
                    self.ctrls[c].SetBackgroundColour(wxRED)
            elif t == "color0":
                # HTML Color field or empty field
                val = guiToUni(self.ctrls[c].GetValue())
                rgb = htmlColorToRgbTuple(val)
                
                if val != "" and rgb is None:
                    self.ctrls[c].SetBackgroundColour(wxRED)
                    fieldsValid = False
                else:
                    self.ctrls[c].SetBackgroundColour(wxWHITE)

        if not fieldsValid:
            self.Refresh()
            return

        # Then transfer options from dialog to config file
        for o, c, t in self.OPTION_TO_CONTROL:
            # TODO Handle unicode text controls
            if t == "b":
                self.pWiki.getConfig().set("main", o, repr(self.ctrls[c].GetValue()))
            elif t in ("t", "tre", "i0+", "f0+", "color0"):
                self.pWiki.getConfig().set(
                        "main", o, guiToUni(self.ctrls[c].GetValue()) )
            elif t == "seli":   # Selection -> transfer index
                self.pWiki.getConfig().set(
                        "main", o, unicode(self.ctrls[c].GetSelection()) )

        # Options with special treatment
        if self.ctrls.cbLowResources.GetValue():
            self.pWiki.getConfig().set("main", "lowresources", "1")
        else:
            self.pWiki.getConfig().set("main", "lowresources", "0")

        if self.ctrls.cbNewWindowWikiUrl.GetValue():
            self.pWiki.getConfig().set("main", "new_window_on_follow_wiki_url", "1")
        else:
            self.pWiki.getConfig().set("main", "new_window_on_follow_wiki_url", "0")

        self.pWiki.getConfig().informChanged()

        evt.Skip()


    def OnSelectFaceHtmlPrev(self, evt):
        dlg = FontFaceDialog(self, -1, self.ctrls.tfFacenameHtmlPreview.GetValue())
        if dlg.ShowModal() == wxID_OK:
            self.ctrls.tfFacenameHtmlPreview.SetValue(dlg.GetValue())
        dlg.Destroy()
        
    def OnSelectPageStatusTimeFormat(self, evt):
        dlg = DateformatDialog(self, -1, self.pWiki, 
                deffmt=self.ctrls.tfPageStatusTimeFormat.GetValue())
        if dlg.ShowModal() == wxID_OK:
            self.ctrls.tfPageStatusTimeFormat.SetValue(dlg.GetValue())
        dlg.Destroy()

    def selectColor(self, tfield):
        rgb = htmlColorToRgbTuple(tfield.GetValue())
        if rgb is None:
            rgb = 0, 0, 0

        color = wxColour(*rgb)
        colordata = wxColourData()
        colordata.SetColour(color)

        dlg = wxColourDialog(self, colordata)
        if dlg.ShowModal() == wxID_OK:
            color = dlg.GetColourData().GetColour()
            if color.Ok():
                tfield.SetValue(
                        rgbToHtmlColor(color.Red(), color.Green(), color.Blue()))

        dlg.Destroy()
